<a href="https://colab.research.google.com/github/JiawenAi/MSSP6070/blob/main/WeeklyModules/Week06/PARTICIPATION_ACTIVITY_Week_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import userdata
import os
import subprocess
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

github_token = userdata.get('Git_key')

owner = 'JiawenAi'
repository = 'MSSP6070'

clone_url = f'https://{github_token}@github.com/{owner}/{repository}.git'

# Clone the repository
subprocess.run(['git', 'clone', clone_url])

# Move into the repository
os.chdir(repository)

In [2]:
df = pd.read_csv("data/Student Performance Data.csv")
df.head()

,gender,race/ethnicity,parental level of education,lunch,math score,reading score,writing score,total score,test preparation course,admission prospect
0,female,group B,bachelor's degree,standard,72,72,74,218,none,medium
1,female,group C,some college,standard,69,90,88,247,completed,high
2,female,group B,master's degree,standard,90,95,93,278,none,high
3,male,group A,associate's degree,free/reduced,47,57,44,148,none,low
4,male,group C,some college,standard,76,78,75,229,none,high

In [3]:
df.isna().sum()

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
math score                     0
reading score                  0
writing score                  0
total score                    0
test preparation course        0
admission prospect             0
dtype: int64

In [4]:
#new dataframe that contains the average score of the three subject
#only keep the numerical columns
score_average = lambda x: x.assign(
    average_score=(x['total score'] / 3).round(2)
).select_dtypes(include='number')

new_df = score_average(df)

new_df.head()

   math score  reading score  writing score  total score  average_score
0          72             72             74          218          72.67
1          69             90             88          247          82.33
2          90             95             93          278          92.67
3          47             57             44          148          49.33
4          76             78             75          229          76.33