<a href="https://colab.research.google.com/github/JiawenAi/MSSP6070/blob/main/WeeklyModules/Week05/PARTICIPATION_ACTIVITY_Week_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import userdata
import os
import subprocess

github_token = userdata.get('Git_key')

owner = 'JiawenAi'
repository = 'MSSP6070'

clone_url = f'https://{github_token}@github.com/{owner}/{repository}.git'

# Clone the repository
subprocess.run(['git', 'clone', clone_url])

# Move into the repository
os.chdir(repository)

import pandas as pd

In [2]:
#2b Read each file into a dataframe
aapl = pd.read_csv("data/Week 05 Examples/aapl.csv")
amzn = pd.read_csv("data/Week 05 Examples/amzn.csv")
fb = pd.read_csv("data/Week 05 Examples/fb.csv")
goog = pd.read_csv("data/Week 05 Examples/goog.csv")
nflx = pd.read_csv("data/Week 05 Examples/nflx.csv")

In [3]:
#2c Add a "ticker" column to each dataframe
aapl["ticker"] = "AAPL"
amzn["ticker"] = "AMZN"
fb["ticker"] = "FB"
goog["ticker"] = "GOOG"
nflx["ticker"] = "NFLX"

In [4]:
#2d Append each file together into a single dataframe
faang = pd.concat([aapl, amzn, fb, goog, nflx], ignore_index=True)


#2e save to a csv
faang.to_csv("data/Week 05 Examples/faang.csv", index=False)

In [5]:
!ls "data/Week 05 Examples"

aapl.csv  amzn.csv  faang.csv  fb.csv  goog.csv  nflx.csv

In [6]:
#2f change the 'date' column into a 'datetime'
faang = pd.read_csv("data/Week 05 Examples/faang.csv")
faang.dtypes
faang["date"] = pd.to_datetime(faang["date"])
# turn 'volume' column into integers
faang["volume"] = faang["volume"].astype(int)

#sort by 'date' and 'ticker.'
#Firstly, sort it with dates; if dates are the same, then sort it with ticker
faang = faang.sort_values(["date", "ticker"])

In [7]:
#2g Find the seven rows within the highest value for volume.
faang.nlargest(7, "volume")

          date      open      high       low     close     volume ticker
644 2018-07-26  174.8900  180.1300  173.7500  176.2600  169803668     FB
555 2018-03-20  167.4700  170.2000  161.9500  168.1500  129851768     FB
559 2018-03-26  160.8200  161.1000  149.0200  160.0600  126116634     FB
556 2018-03-21  164.8000  173.4000  163.3000  169.3900  106598834     FB
182 2018-09-21  219.0727  219.6482  215.6097  215.9768   96246748   AAPL
245 2018-12-21  156.1901  157.4845  148.9909  150.0862   95744384   AAPL
212 2018-11-02  207.9295  211.9978  203.8414  205.8755   91328654   AAPL

In [8]:
#2h Use the melt() method to make the 'date' and 'ticker' key identifiers.
# Melt the remaining columns so that there are not separated.
melt_faang = faang.melt(
    id_vars=["date", "ticker"]
)
melt_faang.head(10)

        date ticker variable      value
0 2018-01-02   AAPL     open   166.9271
1 2018-01-02   AMZN     open  1172.0000
2 2018-01-02     FB     open   177.6800
3 2018-01-02   GOOG     open  1048.3400
4 2018-01-02   NFLX     open   196.1000
5 2018-01-03   AAPL     open   169.2521
6 2018-01-03   AMZN     open  1188.3000
7 2018-01-03     FB     open   181.8800
8 2018-01-03   GOOG     open  1064.3100
9 2018-01-03   NFLX     open   202.0500