<a href="https://colab.research.google.com/github/JiawenAi/MSSP6070/blob/main/WeeklyModules/Week05/PARTICIPATION_ACTIVITY_Week_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import os

from google.colab import userdata
token = userdata.get('Git_key')
!git clone https://x-access-token:{token}@github.com/JiawenAi/MSSP6070.git
%cd /content/MSSP6070
!ls "data/Week 05 Examples"

Cloning into 'MSSP6070'...
remote: Enumerating objects: 157, done.
remote: Counting objects: 100% (157/157), done.
remote: Compressing objects: 100% (134/134), done.
remote: Total 157 (delta 49), reused 4 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (157/157), 7.46 MiB | 5.25 MiB/s, done.
Resolving deltas: 100% (49/49), done.
/content/MSSP6070
aapl.csv  amzn.csv  fb.csv  goog.csv  nflx.csv

In [4]:
#2b Read each file into a dataframe
aapl = pd.read_csv("data/Week 05 Examples/aapl.csv")
amzn = pd.read_csv("data/Week 05 Examples/amzn.csv")
fb = pd.read_csv("data/Week 05 Examples/fb.csv")
goog = pd.read_csv("data/Week 05 Examples/goog.csv")
nflx = pd.read_csv("data/Week 05 Examples/nflx.csv")

In [5]:
#2c Add a "ticker" column to each dataframe
aapl["ticker"] = "AAPL"
amzn["ticker"] = "AMZN"
fb["ticker"] = "FB"
goog["ticker"] = "GOOG"
nflx["ticker"] = "NFLX"

In [7]:
#2d Append each file together into a single dataframe
faang = pd.concat([aapl, amzn, fb, goog, nflx], ignore_index=True)


#2e save to a csv
faang.to_csv("data/Week 05 Examples/faang.csv", index=False)

         date      open      high       low     close    volume ticker
0  2018-01-02  166.9271  169.0264  166.0442  168.9872  25555934   AAPL
1  2018-01-03  169.2521  171.2337  168.6929  168.9578  29517899   AAPL
2  2018-01-04  169.2619  170.1742  168.8106  169.7426  22434597   AAPL
3  2018-01-05  170.1448  172.0381  169.7622  171.6751  23660018   AAPL
4  2018-01-08  171.0375  172.2736  170.6255  171.0375  20567766   AAPL

In [8]:
!ls "data/Week 05 Examples"

aapl.csv  amzn.csv  faang.csv  fb.csv  goog.csv  nflx.csv

In [10]:
#2f change the 'date' column into a 'datetime'
faang = pd.read_csv("data/Week 05 Examples/faang.csv")
faang.dtypes
faang["date"] = pd.to_datetime(faang["date"])
# turn 'volume' column into integers
faang["volume"] = faang["volume"].astype(int)

#sort by 'date' and 'ticker.'
#Firstly, sort it with dates; if dates are the same, then sort it with ticker
faang = faang.sort_values(["date", "ticker"])

In [11]:
#2g Find the seven rows within the highest value for volume.
faang.nlargest(7, "volume")

          date      open      high       low     close     volume ticker
644 2018-07-26  174.8900  180.1300  173.7500  176.2600  169803668     FB
555 2018-03-20  167.4700  170.2000  161.9500  168.1500  129851768     FB
559 2018-03-26  160.8200  161.1000  149.0200  160.0600  126116634     FB
556 2018-03-21  164.8000  173.4000  163.3000  169.3900  106598834     FB
182 2018-09-21  219.0727  219.6482  215.6097  215.9768   96246748   AAPL
245 2018-12-21  156.1901  157.4845  148.9909  150.0862   95744384   AAPL
212 2018-11-02  207.9295  211.9978  203.8414  205.8755   91328654   AAPL

In [14]:
#2h Use the melt() method to make the 'date' and 'ticker' key identifiers.
# Melt the remaining columns so that there are not separated.
melt_faang = faang.melt(
    id_vars=["date", "ticker"]
)
melt_faang.head(10)

        date ticker variable      value
0 2018-01-02   AAPL     open   166.9271
1 2018-01-02   AMZN     open  1172.0000
2 2018-01-02     FB     open   177.6800
3 2018-01-02   GOOG     open  1048.3400
4 2018-01-02   NFLX     open   196.1000
5 2018-01-03   AAPL     open   169.2521
6 2018-01-03   AMZN     open  1188.3000
7 2018-01-03     FB     open   181.8800
8 2018-01-03   GOOG     open  1064.3100
9 2018-01-03   NFLX     open   202.0500