<a href="https://colab.research.google.com/github/JiawenAi/MSSP6070/blob/main/WeeklyModules/Week04/Participation_Activity_Week04_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [32]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [33]:
import numpy as np
import pandas as pd

#change the working directory to where I uploaded my data：
%pushd "/content/drive/MyDrive/MSSP607/WeeklyModules/Week04"

df = pd.read_csv("parsed.csv")
df.head()
df['parsed_place'].head() #the locations
df['mag'].head() #magnitude
df['magType'].head() #type of magnitude
df['tsunami'].head() #have tsunami or not (true 1 /false 0)

/content/drive/MyDrive/MSSP607/WeeklyModules/Week04

0    0
1    0
2    0
3    0
4    0
Name: tsunami, dtype: int64

In [34]:
#2a Find the 95th percentile of earthquake magnitude in Japan using magType of 'mb'
#find Japan earthquake，and magType is mb
japan_mb= df[df['parsed_place'].str.endswith('Japan') &
    (df['magType'] == 'mb')]

#find the 95th percentile
percentile_95 = np.percentile(japan_mb['mag'], 95)
print("The 95th percentile of earthquake magnitutde in japan is:", percentile_95)

The 95th percentile of earthquake magnitutde in japan is: 4.9

In [35]:
#2b Find the percentage of earthquakes in Indonesia that were coupled with tsunamis.

#find indonesia data
indonesia = df[df['parsed_place'].str.endswith('Indonesia')]

#find indonesia tsunami data
indonesia_tsunami = indonesia[indonesia['tsunami'] == 1]

percentage_indonesia_tsunami = (len(indonesia_tsunami) / len(indonesia)) * 100

print("The percentage of earthquakes in Indonesia that were coupled with tsunamis is:",
      f'{percentage_indonesia_tsunami:.2f}%')

The percentage of earthquakes in Indonesia that were coupled with tsunamis is: 23.13%

In [36]:
#2c Get summary statistics for earthquakes in Nevada
#find Nevada earthquakes data
nevada_data = df[df['parsed_place'].str.endswith('Nevada')]
nevada_data.describe()

,cdi,dmin,felt,gap,mag,mmi,nst,rms,sig,time,tsunami,tz,updated
count,15.000000,681.000000,15.000000,681.000000,681.000000,1.00,681.000000,681.000000,681.000000,6.810000e+02,681.0,681.0,6.810000e+02
mean,2.440000,0.166199,2.400000,153.668120,0.500073,2.84,12.618209,0.151986,10.970631,1.538314e+12,0.0,-480.0,1.538402e+12
std,0.501142,0.166228,4.626013,68.735302,0.696710,NaN,9.866963,0.084662,19.607150,5.965637e+08,0.0,0.0,6.010951e+08
min,2.000000,0.001000,1.000000,29.140000,-0.500000,2.84,3.000000,0.000500,0.000000,1.537247e+12,0.0,-480.0,1.537307e+12
25%,2.000000,0.053000,1.000000,97.380000,-0.100000,2.84,6.000000,0.106900,0.000000,1.537854e+12,0.0,-480.0,1.537928e+12
50%,2.200000,0.112000,1.000000,149.140000,0.400000,2.84,10.000000,0.146300,2.000000,1.538280e+12,0.0,-480.0,1.538428e+12
75%,2.900000,0.233000,1.000000,199.720000,0.900000,2.84,16.000000,0.187100,12.000000,1.538821e+12,0.0,-480.0,1.538878e+12
max,3.300000,1.414000,19.000000,355.910000,2.900000,2.84,61.000000,0.863400,129.000000,1.539461e+12,0.0,-480.0,1.539483e+12

In [37]:
#2d Add a column to the dataframe
#indicating whether or not the earthquake happened in a country or US state that is on the Ring of Fire.
df['ring_of_fire'] = ''
df.columns

Index(['alert', 'cdi', 'code', 'detail', 'dmin', 'felt', 'gap', 'ids', 'mag',
       'magType', 'mmi', 'net', 'nst', 'place', 'rms', 'sig', 'sources',
       'status', 'time', 'title', 'tsunami', 'type', 'types', 'tz', 'updated',
       'url', 'parsed_place', 'ring_of_fire'],
      dtype='object')

In [38]:
df['ring_of_fire'] = df.parsed_place.str.contains(r'|'.join([
        'Bolivia', 'Chile', 'Ecuador', 'Peru', 'Costa Rica',
        'Guatemala', '^Mexico', 'Japan', 'Philippines', 'Indonesia',
        'New Zealand', 'Antarctic', 'Canada', 'Fiji',
        'Alaska', 'Washington', 'California', 'Russia',
        'Taiwan', 'Tonga', 'Kermadec Islands'
    ]))

df[['ring_of_fire', 'parsed_place']]

      ring_of_fire parsed_place
0             True   California
1             True   California
2             True   California
3             True   California
4             True   California
...            ...          ...
9327          True   California
9328          True   California
9329         False  Puerto Rico
9330          True   California
9331          True   California

[9332 rows x 2 columns]

In [39]:
#2e Calculate the number of earthquakes in the Ring of Fire locations and the number outside of them

df['ring_of_fire'].value_counts()

ring_of_fire
True     7188
False    2144
Name: count, dtype: int64

In [40]:
ring_counts = df['ring_of_fire'].value_counts()
print('Number of earthquakes in the Ring of Fire:', ring_counts[True])
print('Number of earthquakes outside the Ring of Fire:', ring_counts[False])

Number of earthquakes in the Ring of Fire: 7188
Number of earthquakes outside the Ring of Fire: 2144

In [41]:
#2f Find the tsunami count along the Ring of Fire
fire_with_tsunami = df[(df['ring_of_fire'] == True) & (df['tsunami'] == 1)]

print('Number of Tsunami with the Ring of Fire:',len(fire_with_tsunami))

Number of Tsunami with the Ring of Fire: 45